spring:
  application:
    name: blog
  datasource:
    username: fanqie
    password: 1125
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.31.216:5432/blog
  sql:
    init:
      mode: always
  data:
    redis:
      host: 192.168.31.216
      port: 6379
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    map-underscore-to-camel-case: true