spring:
  application:
    name: blog
  datasource:
    username: fanqie
    password: 1125
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/blog
  sql:
    init:
      mode: always
  data:
    redis:
      host: 127.0.0.1
      port: 6379
logging:
  level:
    com.baomidou.mybatisplus: debug
    org.apache.ibatis: debug
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


